version: '3.8'
services:
  tomcat11-manager-on-servlet-api:
    image: onfocus0147/tomcat11-manager:latest
    ports:
#     expose tomcat port 8080(container) on host as port 8888(host)
      - "8888:8080"
#     expose java debugging port 5005 on host as port 5005  (HOST:CONTAINER)
      - "5005:5005"
#    command: "catalina.sh run"
    command:
      - /bin/sh
      - -c
      - cp target/*.war /usr/local/tomcat/webapps && ls && catalina.sh run
    volumes:
#     "host path to the directory with .war file" / "container tomcat directory with webapps"
      - "./target:/usr/local/tomcat/target"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
#      JAVA_OPTS: "JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  tomcat11-manager-on-servlet-api-exploded:
    image: onfocus0147/tomcat11-manager:latest
    ports:
      #     expose tomcat port 8080(container) on host as port 8888(host)
      - "8888:8080"
      #     expose java debugging port 5005 on host as port 5005  (HOST:CONTAINER)
      - "5005:5005"
    command: "catalina.sh run"
    volumes:
      #     "host path to the directory with .war file" / "container tomcat directory with webapps"
      - "./target:/usr/local/tomcat/webapps"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
#      JAVA_OPTS: "JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
